/* CONFIGURATION CONSTANTS */

const MAX_CONNECTIONS_PER_STUDENT = 3;
const NOTIFICATION_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
const CLEANUP_INTERVAL_MS = 60 * 1000; // 1 min

export {
  MAX_CONNECTIONS_PER_STUDENT,
  NOTIFICATION_TTL_MS,
  CLEANUP_INTERVAL_MS,
};